---
- name: restart wireguard
  systemd:
    name: "wg-quick@{{ wireguard_interface }}"
    daemon_reload: yes
    state: restarted

- name: restart nftables
  systemd:
    name: nftables
    daemon_reload: yes
    state: restarted
