---
- name: Generate client configuration
  template:
    src: wg0-client.conf.j2
    dest: "{{ wireguard_config_dir }}/{{ wireguard_interface }}.conf"
    mode: '0600'
    owner: root
    group: root
  notify:
    - restart wireguard

- name: Configure firewall for client
  include_tasks: firewall.yml
  vars:
    firewall_action: client

- name: Enable and start WireGuard service
  systemd:
    name: "wg-quick@{{ wireguard_interface }}"
    enabled: yes
    state: started
    daemon_reload: yes

- name: Display client public key
  debug:
    msg: |
      Client public key: {{ wireguard_public_key }}
      Add this to server configuration:
      [Peer]
      PublicKey = {{ wireguard_public_key }}
      AllowedIPs = {{ wireguard_client_ip }}