---
- name: Install WireGuard (Ubuntu/Debian)
  apt:
    name:
      - wireguard
      - wireguard-tools
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Enable IP forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes
  when: wireguard_role == "server"