---
- name: Generate server configuration
  template:
    src: wg0-server.conf.j2
    dest: "{{ wireguard_config_dir }}/{{ wireguard_interface }}.conf"
    mode: '0600'
    owner: root
    group: root
  notify:
    - restart wireguard

- name: Configure firewall for server
  include_tasks: firewall.yml
  vars:
    firewall_action: server

- name: Enable and start WireGuard service
  systemd:
    name: "wg-quick@{{ wireguard_interface }}"
    enabled: yes
    state: started
    daemon_reload: yes

- name: Display server public key
  debug:
    msg: "Server public key: {{ wireguard_public_key }}"