name: Deploy to local network

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run Ansible playbook
        working-directory: ./erosion-portal
        run: |
          source ~/.venvs/ansible/bin/activate
          ansible-playbook -i hosts.yml deploy-core.yml --limit explosivo --check
